export const SCREENS = {
  WELCOME: 'welcome',
  LOGIN: 'login',
  REGISTRATION: 'registration',
  HOME: 'home',
  SYMPTOMS: 'symptoms',
  CARE_GUIDANCE: 'care_guidance',
  HEALTHCARE: 'healthcare',
  FACILITY_DETAILS: 'facility_details',
  AVAILABILITY: 'availability',
  BOOKING: 'booking',
  APPOINTMENT_CONFIRMED: 'appointment_confirmed',
  APPOINTMENTS: 'appointments',
  REFERRAL: 'referral',
  TRACK_REFERRAL: 'track_referral',
  HEALTH_JOURNEY: 'health_journey',
  FOLLOW_UP: 'follow_up',
  SCHEMES: 'schemes',
  SCHEME_DETAILS: 'scheme_details',
  MOBILE_CLINIC: 'mobile_clinic',
  ABHA: 'abha',
}

export const SCREEN_TITLES = {
  [SCREENS.WELCOME]: 'Rural Care Navigator',
  [SCREENS.LOGIN]: 'Patient Login',
  [SCREENS.REGISTRATION]: 'Patient Registration',
  [SCREENS.HOME]: 'Rural Care Navigator',
  [SCREENS.SYMPTOMS]: 'Check Symptoms',
  [SCREENS.CARE_GUIDANCE]: 'Care Guidance',
  [SCREENS.HEALTHCARE]: 'Nearby Healthcare',
  [SCREENS.FACILITY_DETAILS]: 'Facility Details',
  [SCREENS.AVAILABILITY]: 'Doctor Availability',
  [SCREENS.BOOKING]: 'Book Appointment',
  [SCREENS.APPOINTMENT_CONFIRMED]: 'Booking Confirmed',
  [SCREENS.APPOINTMENTS]: 'My Appointments',
  [SCREENS.REFERRAL]: 'Care Referral',
  [SCREENS.TRACK_REFERRAL]: 'Track Referral Status',
  [SCREENS.HEALTH_JOURNEY]: 'My Health Journey',
  [SCREENS.FOLLOW_UP]: 'Care Follow-up',
  [SCREENS.SCHEMES]: 'Government Schemes',
  [SCREENS.SCHEME_DETAILS]: 'Scheme Details',
  [SCREENS.MOBILE_CLINIC]: 'Mobile Clinic Schedule',
  [SCREENS.ABHA]: 'ABHA Health Card',
}

export const BOTTOM_NAV_ITEMS = [
  { id: SCREENS.HOME, label: 'Home', icon: '🏠' },
  { id: SCREENS.CARE_GUIDANCE, label: 'Guidance', icon: '🩺' },
  { id: SCREENS.APPOINTMENTS, label: 'Visits', icon: '📅' },
  { id: SCREENS.SCHEMES, label: 'Schemes', icon: '📋' },
  { id: SCREENS.ABHA, label: 'ABHA', icon: '🪪' },
]
